### PR TITLE
27 hibernate integration initial sprint

### LINKED ISSUE #27: hibernate-integration

### PR DESCRIPTION
**Pull request by jomariabejo**

### CODE REVIEW

**Review by mmdc-j-abejo — APPROVED** [review]
first blood

**Review by mmdc-j-abejo — APPROVED** [review]

**Review by jomariabejo — COMMENTED** [review]
common change request success

**Review by mmdc-j-abejo — APPROVED** [review]

**Review by jomariabejo — COMMENTED** [review]
asdf

**Review by mmdc-j-abejo — APPROVED** [review]

**Review by mmdc-j-abejo — APPROVED** [review]

**Review by mmdc-j-abejo — APPROVED** [review]

**Comment by jomariabejo** [comment]
**HumanResourceOnAction**
image
### Implement the following features for hr admin:

1. Create Dashboard
   - [ ] Payroll Expense Trend
   - [ ] Payroll Cost By Department
   - [ ] Employee Benefit Distribution
   - [ ] Cumulative Payroll Expense
 2. Implement employees tab view
    - [ ] Display entire employees
    - [ ] Add new employee
    - [ ] Add multiple employee
    - [ ] Add On Action btns for table view including Edit,Update & Delete
    - [ ] Make pagination responsive
 3. Implement timesheets tab view
    - [ ] Display entire timesheets
    - [ ] Can CRUD timesheet for specific employee
    - [ ] Add multiple employee
    - [ ] Make employee pagination responsive
  4. Implement leave request tab view
    - [ ]  Create **Accept**/**Reject** leave requests
    - [ ]  View leave requests tableview 
    - [ ] Add pagination if possible
  5. Overtime 
    - [ ] Can **Accept**/**Reject** overtime requests
    - [ ] View overtime requests

**Pull request merged**
